//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" recipe.
//
// The Module class derives from the CAB base class ModuleInit and it will be instantiated
// when the module is loaded by the CAB infrastructure.
//
// 
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

//using Jurassic.AppCenter.AppServices;
using Jurassic.AppCenter.SmartClient.Infrastructure.Interface;
using Microsoft.Practices.CompositeUI;
using Microsoft.Practices.ObjectBuilder;

namespace Jurassic.So.GeoTopic.SubmissionTool
{
    public class Module : ModuleInit
    {
        private WorkItem _rootWorkItem;

        [InjectionConstructor]
        public Module([ServiceDependency] WorkItem rootWorkItem)
        {
            _rootWorkItem = rootWorkItem;
        }

        /// <summary>
        /// 注册服务
        /// </summary>
        public override void AddServices()
        {
            /// 生成WCF服务代理，其中ISomeWcfService是服务协议
            //ISomeWcfService _service = _rootWorkItem.Services.Get<ClientManager>()
            //    .GetClient<ISomeWcfService>();
            //_rootWorkItem.Services.Add<ISomeWcfService>(_service);

            //生成本地服务
            //ISomeLocalService _service = _rootWorkItem.Services.AddNew<SomeLocalServiceImpl, ISomeLocalService>();
        }


        public override void Load()
        {
            base.Load();

            _rootWorkItem.WorkItems.AddNew<ControlledWorkItem<ModuleController>>();
            //workItem.Controller.Run();
        }
    }
}
