//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" recipe.
//
// This class contains placeholder methods for the common module initialization 
// tasks, such as adding services, or user-interface element
//
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using System.Windows.Forms;
using Microsoft.Practices.CompositeUI;
using Microsoft.Practices.CompositeUI.Commands;
using Jurassic.AppCenter.SmartClient.Infrastructure.Interface;
using Jurassic.AppCenter.SmartClient.Infrastructure.Interface.Constants;
using Jurassic.So.GeoTopic.SubmissionTool.Views;
//using Infragistics.Practices.CompositeUI.WinForms;
using Infragistics.Win.UltraWinToolbars;
using Microsoft.Practices.CompositeUI.EventBroker;
using System.ComponentModel;
using Jurassic.So.GeoTopic.SubmissionTool.Services;

namespace Jurassic.So.GeoTopic.SubmissionTool
{
    public class ModuleController : WorkItemController
    {
        public override void Run()
        {
            AddServices();
            ExtendMenu();
            ExtendToolStrip();
            AddViews();
        }

        /// <summary>提交服务</summary>
        internal SubmissionService SubmissionService { get; private set; }
        private void AddServices()
        {
            //TODO: add services provided by the Module. See: Add or AddNew method in 
            //		WorkItem.Services collection
            this.SubmissionService = new SubmissionService();
            //this.SubmissionService.WorkItem = this.WorkItem.;
            this.SubmissionService.Initialize();

        }

        private void ExtendMenu()
        {
            //TODO: add menu items here, normally by calling the "Add" method on
            //		on the WorkItem.UIExtensionSites collection.
            //		

        }

        private void ExtendToolStrip()
        {
            //TODO: add new items to the ToolStrip in the Shell. See the UIExtensionSites collection in the WorkItem. 
            //		
        }

        private void AddViews()
        {
            CreateAndActivateChildForm<ChildView>("ChildView");
        }

        private void RegisterCommands()
        {
            //this.WorkItem.Commands.Add(new Command())
        }


        //TODO: Add CommandHandlers and/or Event Subscriptions
        //		
        //
    }
}
